"""create_initial_tables

Revision ID: 0e80cb8fe26e
Revises: 
Create Date: 2026-10-09 09:30:53.039175

每个迁移脚本都必须实现 downgrade —— 允许降级是能安全试错的前提。
没有 downgrade 的迁移，一旦上线就只能手工修表，
而手工修表正是文档 04 第 5 章明令禁止的做法。
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0e80cb8fe26e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_config',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index('idx_articles_created', ['created_at'], unique=False)
        batch_op.create_index('idx_articles_status_published', ['status', 'published_at'], unique=False)

    op.create_table('article_tags',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    with op.batch_alter_table('article_tags', schema=None) as batch_op:
        batch_op.create_index('idx_article_tags_tag', ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_tags', schema=None) as batch_op:
        batch_op.drop_index('idx_article_tags_tag')

    op.drop_table('article_tags')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('idx_articles_status_published')
        batch_op.drop_index('idx_articles_created')

    op.drop_table('articles')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('site_config')
    # ### end Alembic commands ###
